import { useEffect, useState } from "react";
import { api } from "./lib/api.js";

const nav = [["grid", "Overview"], ["building", "Societies"], ["users", "Residents"], ["card", "Billing & payments"], ["chat", "Complaints"], ["user", "Visitors"], ["chart", "Reports"], ["settings", "Settings"]];
const demoSocieties = [{ id: "greenfield", name: "Greenfield Heights", city: "Gurugram", homes: 286, rate: 97 }, { id: "palm", name: "Palm Residency", city: "Noida", homes: 418, rate: 95 }, { id: "lakeview", name: "Lakeview Enclave", city: "Delhi", homes: 192, rate: 89 }];
const demoRecords = { Residents: [["Aarav Sharma", "Greenfield Heights", "B-1204", "Active"], ["Meera Kapoor", "Palm Residency", "C-802", "Active"]], "Billing & payments": [["September maintenance", "Greenfield Heights", "Rs 3.4L", "97% paid"], ["September maintenance", "Palm Residency", "Rs 4.8L", "95% paid"]], Complaints: [["Water pressure issue", "Flat B-1204", "High", "In progress"], ["Lift maintenance", "Tower C", "Normal", "Assigned"]], Visitors: [["Vikram Mehta", "Flat B-1204", "Today", "Pending"]] };

function Icon({ name }) { const paths = { grid: "M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z", building: "M3 21h18M5 21V8l7-5 7 5v13M9 21v-5h6v5M8 10h.01M12 10h.01M16 10h.01", users: "M16 20v-1.5a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4V20M9 10a4 4 0 1 0-8 0 4 4 0 0 0 8 0M22 20v-1.5a4 4 0 0 0-3-3.87M16 2.13a4 4 0 0 1 0 7.75", card: "M3 5h18v14H3zM3 10h18M7 15h3", chat: "M20 11.5a8 8 0 0 1-8 8 8.4 8.4 0 0 1-3.3-.7L4 20l1.2-4.1A8 8 0 1 1 20 11.5Z", user: "M12 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M4 21a8 8 0 0 1 16 0", chart: "M4 19V5M4 19h17M8 16v-4M12 16V7M16 16v-6M20 16v-9", settings: "M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Z" }; return <svg viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name] || paths.grid} /></svg>; }

function App() {
  const [session, setSession] = useState(() => JSON.parse(localStorage.getItem("societyOS.session") || "null"));
  const [demo, setDemo] = useState(() => !localStorage.getItem("societyOS.session"));
  function onLogin(next) { localStorage.setItem("societyOS.token", next.token); localStorage.setItem("societyOS.session", JSON.stringify(next)); setSession(next); setDemo(false); }
  function onLogout() { localStorage.removeItem("societyOS.token"); localStorage.removeItem("societyOS.session"); setSession(null); setDemo(false); }
  if (!session && !demo) return <Login onLogin={onLogin} onDemo={() => setDemo(true)} />;
  return <Dashboard session={session} demo={demo} onLogout={onLogout} />;
}

function Login({ onLogin, onDemo }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); setBusy(true); setError(""); try { onLogin(await api.login(email, password)); } catch (requestError) { setError(requestError.message); } finally { setBusy(false); } }
  return <div className="auth-shell"><div className="auth-card"><div className="auth-brand"><div className="brand-mark">SO</div><div><strong>societyOS</strong><span>operations suite</span></div></div><p className="eyebrow">Admin access</p><h1>Welcome back.</h1><p className="auth-copy">Sign in to manage live society data.</p><form className="auth-form" onSubmit={submit}><label>Email address<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label>Password<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} required /></label>{error && <p className="login-error">{error}</p>}<button className="primary auth-submit" disabled={busy}>{busy ? "Signing in..." : "Sign in"}</button></form><button className="demo-link" onClick={onDemo}>Preview without login</button></div></div>;
}

function Dashboard({ session, demo, onLogout }) {
  const [active, setActive] = useState("Overview"); const [selected, setSelected] = useState("all"); const [societies, setSocieties] = useState([]); const [dashboard, setDashboard] = useState(null); const [toast, setToast] = useState("");
  const notify = (message) => { setToast(message); window.clearTimeout(window.__societyToast); window.__societyToast = window.setTimeout(() => setToast(""), 2600); };
  useEffect(() => { if (!session) return; api.societies().then(setSocieties).catch(() => notify("Could not load societies from the API")); }, [session]);
  useEffect(() => { if (!session || selected === "all") { setDashboard(null); return; } api.dashboard(selected).then(setDashboard).catch(() => notify("Could not load dashboard data")); }, [session, selected]);
  const workspaceSocieties = societies.length ? societies : demoSocieties;
  const selectedSociety = selected === "all" ? null : workspaceSocieties.find((society) => String(society._id || society.id) === selected);
  const totals = dashboard?.kpis ? { societies: "1", homes: dashboard.kpis.homes, collected: formatCurrency(dashboard.kpis.collected), open: dashboard.kpis.openRequests, rate: `${dashboard.kpis.collectionRate}%` } : { societies: demo ? "12" : "0", homes: demo ? "1,842" : "0", collected: demo ? "Rs 18.6L" : "Rs 0", open: demo ? "28" : "0", rate: demo ? "94.8%" : "0%" };
  const changeModule = (module) => setActive(module);
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">SO</div><div><strong>societyOS</strong><span>operations suite</span></div></div><label className="workspace-label">Workspace<select value={selected} onChange={(event) => setSelected(event.target.value)}><option value="all">All societies</option>{workspaceSocieties.map((society) => <option value={String(society._id || society.id)} key={society._id || society.id}>{society.name}</option>)}</select></label><p className="nav-label">Workspace</p><nav>{nav.slice(0, 6).map(([icon, label]) => <button className={active === label ? "nav-item active" : "nav-item"} onClick={() => changeModule(label)} key={label}><Icon name={icon} />{label}</button>)}</nav><p className="nav-label manage">Manage</p><nav>{nav.slice(6).map(([icon, label]) => <button className={active === label ? "nav-item active" : "nav-item"} onClick={() => changeModule(label)} key={label}><Icon name={icon} />{label}</button>)}</nav><div className="sidebar-spacer" /><div className="profile"><div className="avatar">{(session?.user?.name || "AD").slice(0, 2).toUpperCase()}</div><div><strong>{session?.user?.name || "Workspace admin"}</strong><span>{session?.user?.role || "Demo mode"}</span></div><button className="logout-button" onClick={onLogout}>Log out</button></div></aside><main className="main"><header className="topbar"><button className="menu" onClick={() => document.querySelector(".sidebar").classList.toggle("open")}><span /><span /><span /></button><div className="crumb"><b>Workspace</b> / {active}</div><div className="top-actions"><span className="live-pill">{session ? "API connected" : "Preview mode"}</span></div></header><div className="content">{active === "Overview" ? <Overview data={totals} societies={workspaceSocieties} selectedSociety={selectedSociety} onAction={notify} /> : <ModuleView module={active} societyId={selected === "all" ? "" : selected} societies={workspaceSocieties} data={totals} demo={demo} onBack={() => setActive("Overview")} onAction={notify} />}</div>{toast && <div className="toast">{toast}</div>}</main></div>;
}

function Overview({ data, societies, selectedSociety, onAction }) {
  return <><div className="page-heading"><div><p className="eyebrow">Live workspace</p><h1>Good morning.</h1><p>{selectedSociety ? `${selectedSociety.name} operational summary.` : "Select a society to load its live operational summary."}</p></div><button className="primary" onClick={() => onAction("Open Societies to create a new society")}>＋ Add society</button></div><section className="hero"><div><p className="eyebrow">Portfolio pulse</p><h2>Keep every community moving.</h2><p>Live KPIs replace preview values after selecting a society and signing in.</p><button className="hero-link" onClick={() => onAction("Open Reports to export live records")}>View reports →</button></div><div className="hero-metric"><span>Collection rate</span><strong>{data.rate}</strong><small>Current API value</small></div></section><div className="kpis"><Kpi icon="building" value={data.societies} label="Active societies" tone="blue" /><Kpi icon="users" value={data.homes} label="Homes managed" tone="mint" /><Kpi icon="card" value={data.collected} label="Collected" tone="amber" /><Kpi icon="chat" value={data.open} label="Open requests" tone="rose" /></div><section className="card module-table"><div className="card-head"><div><h2>Society portfolio</h2><p>Choose a society for live modules.</p></div></div><div className="responsive-table"><table><thead><tr><th>Society</th><th>City</th><th>Homes</th><th>Status</th></tr></thead><tbody>{societies.map((society) => <tr key={society._id || society.id}><td data-label="Society"><strong>{society.name}</strong></td><td data-label="City">{society.city || "-"}</td><td data-label="Homes">{society.homes || "-"}</td><td data-label="Status">{society.status || "Live"}</td></tr>)}</tbody></table></div></section></>;
}

function ModuleView({ module, societyId, societies, data, demo, onBack, onAction }) {
  const [records, setRecords] = useState([]); const [query, setQuery] = useState(""); const [showForm, setShowForm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const config = moduleConfig[module];
  async function load() { if (demo) return []; if (module === "Societies") return api.societies(); if (!societyId) return []; return (api[config.loader])(societyId); }
  useEffect(() => { let active = true; setError(""); load().then((items) => active && setRecords(items)).catch((loadError) => active && setError(loadError.message)); return () => { active = false; }; }, [module, societyId]);
  const visible = records.filter((record) => JSON.stringify(record).toLowerCase().includes(query.toLowerCase()));
  const rows = records.length ? visible.map((record) => recordToRow(module, record)) : (demo ? (demoRecords[module] || []) : []);
  async function submit(payload) { setBusy(true); setError(""); try { if (module === "Societies") await api.createSociety(payload); else if (!societyId) throw new Error("Select a society first"); else await api[config.creator](societyId, payload); setShowForm(false); setRecords(await load()); onAction(`${config.title} record created`); } catch (submitError) { setError(submitError.message); } finally { setBusy(false); } }
  function exportCsv() { downloadCsv(`${module.toLowerCase().replaceAll(" ", "-")}.csv`, rows); }
  return <div className="module-view"><div className="module-heading"><div><button className="back-link" onClick={onBack}>← Overview</button><p className="eyebrow">Live module</p><h1>{config.title}</h1><p>{config.subtitle}</p></div><div className="module-actions"><button className="link-button" onClick={exportCsv}>Export CSV</button>{config.fields.length ? <button className="primary" onClick={() => setShowForm((value) => !value)}>＋ {config.action}</button> : null}</div></div>{error && <p className="login-error">{error}</p>}{showForm && <RecordForm fields={config.fields} onCancel={() => setShowForm(false)} onSubmit={submit} busy={busy} societies={societies} />}{module !== "Reports" && <div className="module-toolbar"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder={`Search ${config.title.toLowerCase()}...`} /><span>{records.length || rows.length} records</span></div>}<div className="module-stats"><div className="module-stat"><strong>{records.length || rows.length}</strong><span>Records shown</span></div><div className="module-stat"><strong>{societyId ? "Live" : "Preview"}</strong><span>Data source</span></div><div className="module-stat"><strong>{data.rate}</strong><span>Collection rate</span></div></div><section className="card module-table"><div className="card-head"><div><h2>{config.title} overview</h2><p>API-backed and mobile-friendly.</p></div></div><div className="responsive-table"><table><thead><tr>{config.headers.map((header) => <th key={header}>{header}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={row.join("-") + index}>{row.map((cell, cellIndex) => <td key={`${cell}-${cellIndex}`} data-label={config.headers[cellIndex]}>{cellIndex === 0 ? <strong>{cell}</strong> : cell}</td>)}</tr>)}</tbody></table></div></section></div>;
}

function RecordForm({ fields, onCancel, onSubmit, busy }) { const [values, setValues] = useState({}); return <form className="module-form" onSubmit={(event) => { event.preventDefault(); onSubmit(Object.fromEntries(Object.entries(values).filter(([, value]) => value !== ""))); }}><div className="form-grid">{fields.map((field) => <label key={field.name}>{field.label}<input type={field.type || "text"} required={field.required !== false} value={values[field.name] || ""} onChange={(event) => setValues({ ...values, [field.name]: event.target.value })} placeholder={field.placeholder || ""} /></label>)}</div><div className="form-actions"><button type="button" className="link-button" onClick={onCancel}>Cancel</button><button className="primary" disabled={busy}>{busy ? "Saving..." : "Save record"}</button></div></form>; }

const moduleConfig = { Societies: { title: "Societies", subtitle: "Create and monitor every community.", action: "Add society", loader: "societies", creator: "createSociety", headers: ["Society", "City", "State", "Status"], fields: [{ name: "name", label: "Society name" }, { name: "city", label: "City" }, { name: "state", label: "State" }] }, Residents: { title: "Residents", subtitle: "Manage live resident accounts and flat assignments.", action: "Add resident", loader: "residents", creator: "createResident", headers: ["Resident", "Email", "Flat", "Role"], fields: [{ name: "name", label: "Name" }, { name: "email", label: "Email", type: "email" }, { name: "password", label: "Temporary password", type: "password" }, { name: "flatId", label: "Flat ID" }] }, "Billing & payments": { title: "Billing & payments", subtitle: "Create bills and inspect the payment ledger.", action: "Create bill", loader: "bills", creator: "createBill", headers: ["Bill", "Flat", "Amount", "Status"], fields: [{ name: "flatId", label: "Flat ID" }, { name: "month", label: "Month", type: "number" }, { name: "year", label: "Year", type: "number" }, { name: "amount", label: "Amount", type: "number" }, { name: "dueDate", label: "Due date", type: "date" }] }, Complaints: { title: "Complaints", subtitle: "Track resident requests with accountable status changes.", action: "New complaint", loader: "complaints", creator: "createComplaint", headers: ["Category", "Flat", "Priority", "Status"], fields: [{ name: "flatId", label: "Flat ID" }, { name: "category", label: "Category" }, { name: "description", label: "Description" }, { name: "priority", label: "Priority", required: false }] }, Visitors: { title: "Visitors", subtitle: "Review and register visitor movement.", action: "Register visitor", loader: "visitors", creator: "createVisitor", headers: ["Visitor", "Flat", "Visit date", "Status"], fields: [{ name: "flatId", label: "Flat ID" }, { name: "visitorName", label: "Visitor name" }, { name: "visitorMobile", label: "Mobile", required: false }, { name: "purpose", label: "Purpose", required: false }, { name: "visitDate", label: "Visit date", type: "datetime-local" }] }, Reports: { title: "Reports", subtitle: "Export the currently available live records.", action: "", loader: "payments", creator: "", headers: ["Payment", "Flat", "Amount", "Method"], fields: [] }, Settings: { title: "Settings", subtitle: "Configuration and API connection details.", action: "", loader: "societies", creator: "", headers: ["Setting", "Value", "Status", "Owner"], fields: [] } };

function recordToRow(module, record) { if (module === "Societies") return [record.name, record.city || "-", record.state || "-", record.active === false ? "Inactive" : "Live"]; if (module === "Residents") return [record.name, record.email, record.flatId?.flatNumber || "Unassigned", record.role || "resident"]; if (module === "Billing & payments") return [`${record.month}/${record.year}`, record.flatId?.flatNumber || record.flatId || "-", formatCurrency(record.amount), record.status]; if (module === "Complaints") return [record.category, record.flatId?.flatNumber || record.flatId || "-", record.priority || "normal", record.status]; if (module === "Visitors") return [record.visitorName, record.flatId?.flatNumber || record.flatId || "-", dateText(record.visitDate), record.status]; if (module === "Reports") return [record.billId?.month ? `${record.billId.month}/${record.billId.year}` : "Payment", record.flatId?.flatNumber || "-", formatCurrency(record.amountPaid), record.method || "-" ]; return [module, "Configured in API", "Active", "societyOS"]; }
function formatCurrency(value) { const amount = Number(value || 0); return amount >= 100000 ? `Rs ${(amount / 100000).toFixed(1)}L` : `Rs ${Math.round(amount).toLocaleString("en-IN")}`; }
function dateText(value) { if (!value) return "-"; const date = new Date(value); return Number.isNaN(date.getTime()) ? "-" : date.toLocaleDateString("en-IN"); }
function downloadCsv(name, rows) { const csv = rows.map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(",")).join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }
function Kpi({ icon, value, label, tone }) { return <article className="kpi"><div className={`kpi-icon ${tone}`}><Icon name={icon} /></div><h3>{value}</h3><p>{label}</p></article>; }

export default App;
