import {
  Building,
  Home,
  IndianRupee,
  AlertTriangle,
  Percent,
  ChevronRight,
  ChevronLeft,
  ChevronUp,
  ChevronDown,
  Menu,
  LogOut,
  User,
  Settings,
  Search,
  Plus,
  Edit,
  Trash2,
  Eye,
  Download,
  Upload,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  Check,
  X,
  Loader2,
  RefreshCw,
  Filter,
  MoreHorizontal,
  Bell,
  Shield,
  Key,
  Lock,
  Unlock,
  HelpCircle,
} from 'lucide-react';

const iconMap = {
  building: Building,
  home: Home,
  rupee: IndianRupee,
  'alert-triangle': AlertTriangle,
  percent: Percent,
  'chevron-right': ChevronRight,
  'chevron-left': ChevronLeft,
  'chevron-up': ChevronUp,
  'chevron-down': ChevronDown,
  menu: Menu,
  logout: LogOut,
  user: User,
  settings: Settings,
  search: Search,
  plus: Plus,
  edit: Edit,
  trash: Trash2,
  eye: Eye,
  download: Download,
  upload: Upload,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  calendar: Calendar,
  clock: Clock,
  check: Check,
  x: X,
  loader: Loader2,
  refresh: RefreshCw,
  filter: Filter,
  more: MoreHorizontal,
  bell: Bell,
  shield: Shield,
  key: Key,
  lock: Lock,
  unlock: Unlock,
};

export function Icon({ name, size = 18, className = '', style }) {
  const IconComponent = iconMap[name] || HelpCircle;
  if (!IconComponent) return null;
  return <IconComponent size={size} className={className} style={style} />;
}
